import spacy

nlp = spacy.load("lt_core_news_lg")

def print_pos(sentence):
    doc = nlp(sentence)
    related_entities = []
    for token in doc:
        print(token.text+" "+token.pos_ + "   " + token.lemma_)


##print_pos("Kadangi kiekviena valstybė, kaip matome, yra tam tikra bendrija, o kiekviena bendrija yra susikūrusi dėl kokio nors gėrio (juk visi viską daro to, ką jie laiko gėriu, labui), akivaizdu, kad visos jos siekia kokio nors gėrio, o labiausiai ir aukščiausiojo gėrio siekia ta bendrija, kuri yra visų svarbiausioji ir apima visas kitas; ši bendrija ir vadinama valstybe, arba pilietine bendrija. Tie, kurie mano, kad tai, kas būdinga valstybės vyrui, karaliui, ūkio valdytojui ir šeimininkui, yra tas pat, teigia neteisingai, nes taria, kad kiekvienas iš jų skiriasi tuo, ar jis valdo daugelį, ar nedaugelį, bet ne rūšimi, ir kad valdantis nedaugelį yra šeimininkas, daugiau - ūkio valdytojas, o dar daugiau - valstybės vyras arba karalius, tarsi didelis ūkis niekuo nesiskirtų nuo mažos valstybės, o valstybės vyras nuo karaliaus skirtųsi tik tuo, kad tas, kas valdo vienas pats, yra karalius, o kas pagal tokio [valdymo] mokslo dėsnius pakaitomis valdo ir yra valdomas, tas yra valstybės vyras; tačiau tai nėra teisinga. Tai paaiš¬kės tiriant kalbamąjį dalyką mūsų įprastu būdu: kaip kitais atvejais sudėtinę visumą reikia suskaidyti į nedalijamus elementus (nes tai yra smulkiausios visumos dalelės), taip ir čia nagrinėdami, iš ko susideda valstybė, mes ir apie tas [įvairias valdovų rūšis] įžvelgsime, kas reikia, ir ypač - kuo jie skiriasi vieni nuo kitų ir ar įmanoma moksliš¬kai aptarti kiekvieną iš jų. Kaip kitur, taip ir čia tas, kas nuo pat pradžių stebėtų patį dalykų susidarymą, būtent tokiu būdu pamatytų viską aiškiausiai. 4. Pirmiausia neišvengiamai susijungia į porą tie, kurie vienas be kito negali egzistuoti: moteriškasis ir vyriškasis pradai, kad pratęstų giminę (ir tai lemia ne laisvas pasirinkimas, bet prigimtis, kuri, kaip ir kitų gyvių bei augalų, reikalauja palikti naują į save panašią būtybę), taip pat iš prigimties valdantysis ir valdomasis, kad išgyventų (nes pajėgiantis protu numatyti yra iš prigimties valdantysis ir viršesnis, o pajėgiantis kūno galiomis įvykdyti [jo paliepimus] yra valdomasis ir iš prigimties vergiškas: dėl to tas pat yra naudinga ir šeimininkui, ir vergui). 5. Vis dėlto moteriškasis ir vergiškasis pradai savo prigimtimi yra skirtingi (juk gamta nieko nedaro taip taupiai, kaip kalviai, gaminantys Delfų peilį, ji vieną dalyką skiria vienam tikslui, nes kiekvienas įrankis geriausiai atliks savo paskirtį tarnaudamas ne daugeliui tikslų, bet vienam). Tačiau barbarai moteriai ir vergui skiria tokią pačią vietą — taip yra todėl, kad jie neturi iš prigimties valdančiojo prado, ir jų [vyro ir moters] sąjunga tampa vergo ir vergės sąjunga. Todėl poetai ir sako: turėdami galvoje, kad barbaras ir vergas savo prigimtimi yra tas pat.")
print_pos("Namas yra pastatytas iš plytų")
